language: generic
env:
  - HEAD=yes
  - HEAD=no
sudo: true 

addons:
  apt:
    packages:
      - vim
      - git
      - exuberant-ctags
      - python

install:
  - sudo pip install dbgp vim-debug pep8 flake8 pyflakes isort
  - bash install.sh
