language: generic
env:
  - HEAD=yes
  - HEAD=no
sudo: false

addons:
  apt:
    packages:
      - vim
      - git
      - exuberant-ctags
      - python

install:
  - pip install dbgp vim-debug pep8 flake8 pyflakes isort
  - bash install.sh

before_script:
  - easy_install pip
